apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: portfolio
  namespace: portfolio
spec:
  selector:
    matchLabels:
      app: portfolio
  endpoints:
  - port: http
    interval: 30s
